/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
/home/nacool/Desktop/Projects/scholarship_scraper/venv/bin/python3.9: can't open file '/home/nacool/Desktop/Projects/scholarship_scraper/notifier/mail_notifier.py': [Errno 2] No such file or directory
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
192.168.1.13 - - [08/Jan/2023 13:54:19] "GET / HTTP/1.1" 200 -
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
192.168.1.13 - - [08/Jan/2023 15:55:07] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:00:01] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:04:42] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:05:01] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:10:03] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:15:02] "GET / HTTP/1.1" 200 -
192.168.1.13 - - [08/Jan/2023 16:20:01] "GET / HTTP/1.1" 200 -
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
[2023-01-08 16:22:46,773] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError im22-20020a170902bb1600b0018bc4493005sm3921410plb.269 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:22:46] "[35m[1mGET / HTTP/1.1[0m" 500 -
192.168.1.13 - - [08/Jan/2023 16:22:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-01-08 16:25:04,646] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError e23-20020aa79817000000b00580e526cd33sm4009698pfl.198 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:25:04] "[35m[1mGET / HTTP/1.1[0m" 500 -
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
[2023-01-08 16:25:59,107] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError f78-20020a623851000000b0057726bd7335sm4011455pfa.121 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:25:59] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2023-01-08 16:27:05,534] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError b16-20020a170902d51000b0018b025d9a40sm3930721plg.256 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:27:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2023-01-08 16:34:27,315] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError w6-20020a170902e88600b00189e7cb8b89sm3999168plg.127 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:34:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
[2023-01-08 16:35:10,565] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError t23-20020aa79477000000b00574e84ed847sm4070135pfq.24 - gsmtp', 'nacool.scholarsmate@gmail.com')
192.168.1.13 - - [08/Jan/2023 16:35:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.4:5000 (Press CTRL+C to quit)
[2023-01-08 17:09:30,183] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 90, in send_notification
    return send_mail_and_update(result)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 70, in send_mail_and_update
    send_mail(email, sch)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/parser/notifier/mail_notifier.py", line 82, in send_mail
    mail.send(message)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError l123-20020a622581000000b005818d429d98sm4059330pfl.136 - gsmtp', 'nacool.scholarsmate@gmail.com')
127.0.0.1 - - [08/Jan/2023 17:09:30] "[35m[1mGET / HTTP/1.1[0m" 500 -
127.0.0.1 - - [08/Jan/2023 17:09:30] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
