[2022-08-30 20:40:55 +0530] [527054] [INFO] Starting gunicorn 20.1.0
[2022-08-30 20:40:55 +0530] [527054] [INFO] Listening at: http://0.0.0.0:5080 (527054)
[2022-08-30 20:40:55 +0530] [527054] [INFO] Using worker: sync
[2022-08-30 20:40:55 +0530] [527055] [INFO] Booting worker with pid: 527055
[2022-09-06 23:09:04 +0530] [527054] [INFO] Handling signal: term
[2022-09-06 23:09:05 +0530] [527055] [INFO] Worker exiting (pid: 527055)
[2022-09-06 23:09:09 +0530] [527054] [INFO] Shutting down: Master
[2022-09-08 11:25:59 +0530] [1592] [INFO] Starting gunicorn 20.1.0
[2022-09-08 11:25:59 +0530] [1592] [INFO] Listening at: http://0.0.0.0:5080 (1592)
[2022-09-08 11:25:59 +0530] [1592] [INFO] Using worker: sync
[2022-09-08 11:25:59 +0530] [1684] [INFO] Booting worker with pid: 1684
[2022-09-08 11:26:29 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:1684)
[2022-09-08 11:26:29 +0530] [1684] [INFO] Worker exiting (pid: 1684)
[2022-09-08 11:26:30 +0530] [2099] [INFO] Booting worker with pid: 2099
[2022-09-08 11:27:00 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:2099)
[2022-09-08 11:27:00 +0530] [2099] [INFO] Worker exiting (pid: 2099)
[2022-09-08 11:27:00 +0530] [2812] [INFO] Booting worker with pid: 2812
[2022-09-08 11:27:30 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:2812)
[2022-09-08 11:27:30 +0530] [2812] [INFO] Worker exiting (pid: 2812)
[2022-09-08 11:27:30 +0530] [3868] [INFO] Booting worker with pid: 3868
[2022-09-08 11:28:01 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:3868)
[2022-09-08 11:28:01 +0530] [3868] [INFO] Worker exiting (pid: 3868)
[2022-09-08 11:28:01 +0530] [4852] [INFO] Booting worker with pid: 4852
[2022-09-08 11:28:31 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:4852)
[2022-09-08 11:28:31 +0530] [4852] [INFO] Worker exiting (pid: 4852)
[2022-09-08 11:28:31 +0530] [5220] [INFO] Booting worker with pid: 5220
[2022-09-08 11:29:01 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:5220)
[2022-09-08 11:29:01 +0530] [5220] [INFO] Worker exiting (pid: 5220)
[2022-09-08 11:29:02 +0530] [5264] [INFO] Booting worker with pid: 5264
[2022-09-08 11:29:32 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:5264)
[2022-09-08 11:29:32 +0530] [5264] [INFO] Worker exiting (pid: 5264)
[2022-09-08 11:29:32 +0530] [5658] [INFO] Booting worker with pid: 5658
[2022-09-08 11:52:19 +0530] [1592] [INFO] Handling signal: term
[2022-09-08 11:52:19 +0530] [5658] [INFO] Worker exiting (pid: 5658)
[2022-09-08 11:52:19 +0530] [1592] [INFO] Shutting down: Master
[2022-09-08 11:52:21 +0530] [24628] [INFO] Starting gunicorn 20.1.0
[2022-09-08 11:52:21 +0530] [24628] [INFO] Listening at: http://0.0.0.0:5080 (24628)
[2022-09-08 11:52:21 +0530] [24628] [INFO] Using worker: sync
[2022-09-08 11:52:21 +0530] [24629] [INFO] Booting worker with pid: 24629
[2022-09-08 11:54:14,915] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 31, in index
    return render_template('index.html',data=data,from_page=from_page,to_page=to_page,current=current,next=next_page,previous=previous_page,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/index.html", line 121, in top-level template code
    {% if not data[x]['metadata'][-1]['website'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element -5
[2022-09-08 11:54:15,010] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 17, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-08 12:03:38,697] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 31, in index
    return render_template('index.html',data=data,from_page=from_page,to_page=to_page,current=current,next=next_page,previous=previous_page,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/index.html", line 121, in top-level template code
    {% if not data[x]['metadata'][-1]['website'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element -5
[2022-09-08 12:03:38,838] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 17, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-08 12:06:42 +0530] [24628] [INFO] Handling signal: term
[2022-09-08 12:06:42 +0530] [24629] [INFO] Worker exiting (pid: 24629)
[2022-09-08 12:06:42 +0530] [24628] [INFO] Shutting down: Master
[2022-09-08 12:06:44 +0530] [26848] [INFO] Starting gunicorn 20.1.0
[2022-09-08 12:06:44 +0530] [26848] [INFO] Listening at: http://0.0.0.0:5080 (26848)
[2022-09-08 12:06:44 +0530] [26848] [INFO] Using worker: sync
[2022-09-08 12:06:44 +0530] [26850] [INFO] Booting worker with pid: 26850
[2022-09-08 13:41:44 +0530] [26848] [INFO] Handling signal: term
[2022-09-08 13:41:44 +0530] [26850] [INFO] Worker exiting (pid: 26850)
[2022-09-08 13:41:45 +0530] [26848] [INFO] Shutting down: Master
[2022-09-08 13:41:46 +0530] [45286] [INFO] Starting gunicorn 20.1.0
[2022-09-08 13:41:46 +0530] [45286] [INFO] Listening at: http://0.0.0.0:5080 (45286)
[2022-09-08 13:41:46 +0530] [45286] [INFO] Using worker: sync
[2022-09-08 13:41:46 +0530] [45288] [INFO] Booting worker with pid: 45288
[2022-09-13 16:32:05 +0530] [347174] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:32:05 +0530] [347174] [INFO] Listening at: http://0.0.0.0:5080 (347174)
[2022-09-13 16:32:05 +0530] [347174] [INFO] Using worker: sync
[2022-09-13 16:32:05 +0530] [347175] [INFO] Booting worker with pid: 347175
[2022-09-13 16:32:09,116] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'scholarship_page' did not return a valid response. The function either returned None or ended without a return statement.
[2022-09-13 16:33:52 +0530] [347174] [INFO] Handling signal: term
[2022-09-13 16:33:52 +0530] [347175] [INFO] Worker exiting (pid: 347175)
[2022-09-13 16:33:52 +0530] [347174] [INFO] Shutting down: Master
[2022-09-13 16:33:54 +0530] [347288] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:33:54 +0530] [347288] [INFO] Listening at: http://0.0.0.0:5080 (347288)
[2022-09-13 16:33:54 +0530] [347288] [INFO] Using worker: sync
[2022-09-13 16:33:54 +0530] [347289] [INFO] Booting worker with pid: 347289
[2022-09-13 16:33:58,689] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:34:25,009] ERROR in app: Exception on /view/631989e4254c573c88d5b18b [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:46:03 +0530] [347288] [INFO] Handling signal: term
[2022-09-13 16:46:03 +0530] [347289] [INFO] Worker exiting (pid: 347289)
[2022-09-13 16:46:03 +0530] [347288] [INFO] Shutting down: Master
[2022-09-13 16:46:05 +0530] [348035] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:46:05 +0530] [348035] [INFO] Listening at: http://0.0.0.0:5080 (348035)
[2022-09-13 16:46:05 +0530] [348035] [INFO] Using worker: sync
[2022-09-13 16:46:05 +0530] [348036] [INFO] Booting worker with pid: 348036
[2022-09-13 16:47:13,030] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:47:13,588] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 16:47:58 +0530] [348035] [INFO] Handling signal: term
[2022-09-13 16:47:58 +0530] [348036] [INFO] Worker exiting (pid: 348036)
[2022-09-13 16:47:58 +0530] [348035] [INFO] Shutting down: Master
[2022-09-13 16:47:59 +0530] [348515] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:47:59 +0530] [348515] [INFO] Listening at: http://0.0.0.0:5080 (348515)
[2022-09-13 16:47:59 +0530] [348515] [INFO] Using worker: sync
[2022-09-13 16:47:59 +0530] [348516] [INFO] Booting worker with pid: 348516
[2022-09-13 16:48:50,651] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:48:59,005] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:49:04,449] ERROR in app: Exception on /view/63198b7750f8c732d010ec8f [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:51:42 +0530] [348515] [INFO] Handling signal: term
[2022-09-13 16:51:42 +0530] [348516] [INFO] Worker exiting (pid: 348516)
[2022-09-13 16:51:43 +0530] [348515] [INFO] Shutting down: Master
[2022-09-13 16:51:44 +0530] [348754] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:51:44 +0530] [348754] [INFO] Listening at: http://0.0.0.0:5080 (348754)
[2022-09-13 16:51:44 +0530] [348754] [INFO] Using worker: sync
[2022-09-13 16:51:44 +0530] [348755] [INFO] Booting worker with pid: 348755
[2022-09-13 16:51:54,661] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:52:07,561] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:53:30 +0530] [348754] [INFO] Handling signal: term
[2022-09-13 16:53:30 +0530] [348755] [INFO] Worker exiting (pid: 348755)
[2022-09-13 16:53:30 +0530] [348754] [INFO] Shutting down: Master
[2022-09-13 16:53:32 +0530] [348837] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:53:32 +0530] [348837] [INFO] Listening at: http://0.0.0.0:5080 (348837)
[2022-09-13 16:53:32 +0530] [348837] [INFO] Using worker: sync
[2022-09-13 16:53:32 +0530] [348838] [INFO] Booting worker with pid: 348838
[2022-09-13 16:53:38,071] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 36, in scholarship_page
    return jsonify(scholarship_data),200
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:53:43 +0530] [348837] [INFO] Handling signal: term
[2022-09-13 16:53:43 +0530] [348838] [INFO] Worker exiting (pid: 348838)
[2022-09-13 16:53:43 +0530] [348837] [INFO] Shutting down: Master
[2022-09-13 16:53:45 +0530] [348883] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:53:45 +0530] [348883] [INFO] Listening at: http://0.0.0.0:5080 (348883)
[2022-09-13 16:53:45 +0530] [348883] [INFO] Using worker: sync
[2022-09-13 16:53:45 +0530] [348884] [INFO] Booting worker with pid: 348884
[2022-09-13 16:54:08 +0530] [348883] [INFO] Handling signal: term
[2022-09-13 16:54:08 +0530] [348884] [INFO] Worker exiting (pid: 348884)
[2022-09-13 16:54:08 +0530] [348883] [INFO] Shutting down: Master
[2022-09-13 16:54:09 +0530] [348910] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:09 +0530] [348910] [INFO] Listening at: http://0.0.0.0:5080 (348910)
[2022-09-13 16:54:09 +0530] [348910] [INFO] Using worker: sync
[2022-09-13 16:54:09 +0530] [348911] [INFO] Booting worker with pid: 348911
[2022-09-13 16:54:11,366] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1723, in make_response
    raise TypeError(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1719, in make_response
    rv = self.response_class.force_type(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 268, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1237, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: str() argument 2 must be str, not function
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a type.
[2022-09-13 16:54:17,816] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 16:54:19 +0530] [348910] [INFO] Handling signal: term
[2022-09-13 16:54:19 +0530] [348911] [INFO] Worker exiting (pid: 348911)
[2022-09-13 16:54:20 +0530] [348910] [INFO] Shutting down: Master
[2022-09-13 16:54:21 +0530] [348923] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:21 +0530] [348923] [INFO] Listening at: http://0.0.0.0:5080 (348923)
[2022-09-13 16:54:21 +0530] [348923] [INFO] Using worker: sync
[2022-09-13 16:54:21 +0530] [348924] [INFO] Booting worker with pid: 348924
[2022-09-13 16:54:34 +0530] [348923] [INFO] Handling signal: term
[2022-09-13 16:54:34 +0530] [348924] [INFO] Worker exiting (pid: 348924)
[2022-09-13 16:54:35 +0530] [348923] [INFO] Shutting down: Master
[2022-09-13 16:54:36 +0530] [348942] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:36 +0530] [348942] [INFO] Listening at: http://0.0.0.0:5080 (348942)
[2022-09-13 16:54:36 +0530] [348942] [INFO] Using worker: sync
[2022-09-13 16:54:36 +0530] [348943] [INFO] Booting worker with pid: 348943
[2022-09-13 16:54:38,446] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1723, in make_response
    raise TypeError(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1719, in make_response
    rv = self.response_class.force_type(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 268, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1237, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: str() argument 2 must be str, not function
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a type.
[2022-09-13 16:54:42 +0530] [348942] [INFO] Handling signal: term
[2022-09-13 16:54:42 +0530] [348943] [INFO] Worker exiting (pid: 348943)
[2022-09-13 16:54:42 +0530] [348942] [INFO] Shutting down: Master
[2022-09-13 16:54:43 +0530] [348986] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:43 +0530] [348986] [INFO] Listening at: http://0.0.0.0:5080 (348986)
[2022-09-13 16:54:43 +0530] [348986] [INFO] Using worker: sync
[2022-09-13 16:54:43 +0530] [348987] [INFO] Booting worker with pid: 348987
[2022-09-13 16:55:19 +0530] [348986] [INFO] Handling signal: term
[2022-09-13 16:55:19 +0530] [348987] [INFO] Worker exiting (pid: 348987)
[2022-09-13 16:55:20 +0530] [348986] [INFO] Shutting down: Master
[2022-09-13 16:55:21 +0530] [349029] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:55:21 +0530] [349029] [INFO] Listening at: http://0.0.0.0:5080 (349029)
[2022-09-13 16:55:21 +0530] [349029] [INFO] Using worker: sync
[2022-09-13 16:55:21 +0530] [349030] [INFO] Booting worker with pid: 349030
[2022-09-13 16:56:23 +0530] [349029] [INFO] Handling signal: term
[2022-09-13 16:56:23 +0530] [349030] [INFO] Worker exiting (pid: 349030)
[2022-09-13 16:56:23 +0530] [349029] [INFO] Shutting down: Master
[2022-09-13 16:56:24 +0530] [349097] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:56:24 +0530] [349097] [INFO] Listening at: http://0.0.0.0:5080 (349097)
[2022-09-13 16:56:24 +0530] [349097] [INFO] Using worker: sync
[2022-09-13 16:56:24 +0530] [349098] [INFO] Booting worker with pid: 349098
[2022-09-13 16:58:38 +0530] [349287] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:58:38 +0530] [349287] [INFO] Listening at: http://0.0.0.0:5080 (349287)
[2022-09-13 16:58:38 +0530] [349287] [INFO] Using worker: sync
[2022-09-13 16:58:38 +0530] [349288] [INFO] Booting worker with pid: 349288
[2022-09-13 16:58:43,906] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:58:44,486] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 17:00:23 +0530] [349413] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:00:23 +0530] [349413] [INFO] Listening at: http://0.0.0.0:5080 (349413)
[2022-09-13 17:00:23 +0530] [349413] [INFO] Using worker: sync
[2022-09-13 17:00:23 +0530] [349414] [INFO] Booting worker with pid: 349414
[2022-09-13 17:00:25,971] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return json.loads(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2022-09-13 17:00:26,583] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 19, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 17:00:42 +0530] [349413] [INFO] Handling signal: term
[2022-09-13 17:00:42 +0530] [349414] [INFO] Worker exiting (pid: 349414)
[2022-09-13 17:00:43 +0530] [349413] [INFO] Shutting down: Master
[2022-09-13 17:00:44 +0530] [349466] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:00:44 +0530] [349466] [INFO] Listening at: http://0.0.0.0:5080 (349466)
[2022-09-13 17:00:44 +0530] [349466] [INFO] Using worker: sync
[2022-09-13 17:00:44 +0530] [349467] [INFO] Booting worker with pid: 349467
[2022-09-13 17:00:46,875] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:01:31 +0530] [349501] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:31 +0530] [349501] [INFO] Listening at: http://0.0.0.0:5080 (349501)
[2022-09-13 17:01:31 +0530] [349501] [INFO] Using worker: sync
[2022-09-13 17:01:31 +0530] [349502] [INFO] Booting worker with pid: 349502
[2022-09-13 17:01:31 +0530] [349502] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:31 +0530] [349502] [INFO] Worker exiting (pid: 349502)
[2022-09-13 17:01:31 +0530] [349501] [INFO] Shutting down: Master
[2022-09-13 17:01:31 +0530] [349501] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:32 +0530] [349503] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:32 +0530] [349503] [INFO] Listening at: http://0.0.0.0:5080 (349503)
[2022-09-13 17:01:32 +0530] [349503] [INFO] Using worker: sync
[2022-09-13 17:01:32 +0530] [349504] [INFO] Booting worker with pid: 349504
[2022-09-13 17:01:32 +0530] [349504] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:32 +0530] [349504] [INFO] Worker exiting (pid: 349504)
[2022-09-13 17:01:32 +0530] [349503] [INFO] Shutting down: Master
[2022-09-13 17:01:32 +0530] [349503] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:34 +0530] [349505] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:34 +0530] [349505] [INFO] Listening at: http://0.0.0.0:5080 (349505)
[2022-09-13 17:01:34 +0530] [349505] [INFO] Using worker: sync
[2022-09-13 17:01:34 +0530] [349506] [INFO] Booting worker with pid: 349506
[2022-09-13 17:01:34 +0530] [349506] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:34 +0530] [349506] [INFO] Worker exiting (pid: 349506)
[2022-09-13 17:01:34 +0530] [349505] [INFO] Shutting down: Master
[2022-09-13 17:01:34 +0530] [349505] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:37 +0530] [349509] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:37 +0530] [349509] [INFO] Listening at: http://0.0.0.0:5080 (349509)
[2022-09-13 17:01:37 +0530] [349509] [INFO] Using worker: sync
[2022-09-13 17:01:37 +0530] [349512] [INFO] Booting worker with pid: 349512
[2022-09-13 17:01:37 +0530] [349512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:37 +0530] [349512] [INFO] Worker exiting (pid: 349512)
[2022-09-13 17:01:37 +0530] [349509] [INFO] Shutting down: Master
[2022-09-13 17:01:37 +0530] [349509] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:54 +0530] [349554] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:54 +0530] [349554] [INFO] Listening at: http://0.0.0.0:5080 (349554)
[2022-09-13 17:01:54 +0530] [349554] [INFO] Using worker: sync
[2022-09-13 17:01:54 +0530] [349555] [INFO] Booting worker with pid: 349555
[2022-09-13 17:02:05,522] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:02:28,167] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:03:15 +0530] [349554] [INFO] Handling signal: term
[2022-09-13 17:03:15 +0530] [349555] [INFO] Worker exiting (pid: 349555)
[2022-09-13 17:03:15 +0530] [349554] [INFO] Shutting down: Master
[2022-09-13 17:03:16 +0530] [349637] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:03:16 +0530] [349637] [INFO] Listening at: http://0.0.0.0:5080 (349637)
[2022-09-13 17:03:16 +0530] [349637] [INFO] Using worker: sync
[2022-09-13 17:03:16 +0530] [349638] [INFO] Booting worker with pid: 349638
[2022-09-13 17:03:19,508] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return jsonify(scholarship_data)
NameError: name 'jsonify' is not defined
[2022-09-13 17:03:50 +0530] [349637] [INFO] Handling signal: term
[2022-09-13 17:03:50 +0530] [349638] [INFO] Worker exiting (pid: 349638)
[2022-09-13 17:03:50 +0530] [349637] [INFO] Shutting down: Master
[2022-09-13 17:03:51 +0530] [349695] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:03:51 +0530] [349695] [INFO] Listening at: http://0.0.0.0:5080 (349695)
[2022-09-13 17:03:51 +0530] [349695] [INFO] Using worker: sync
[2022-09-13 17:03:51 +0530] [349696] [INFO] Booting worker with pid: 349696
[2022-09-13 17:03:55,893] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:06:47 +0530] [349695] [INFO] Handling signal: term
[2022-09-13 17:06:47 +0530] [349696] [INFO] Worker exiting (pid: 349696)
[2022-09-13 17:06:48 +0530] [349695] [INFO] Shutting down: Master
[2022-09-13 17:06:49 +0530] [349890] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:06:49 +0530] [349890] [INFO] Listening at: http://0.0.0.0:5080 (349890)
[2022-09-13 17:06:49 +0530] [349890] [INFO] Using worker: sync
[2022-09-13 17:06:49 +0530] [349891] [INFO] Booting worker with pid: 349891
[2022-09-13 17:07:02,853] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 39, in scholarship_page
    return json.loads(json_util.dumps(scholarship_data))
NameError: name 'json_util' is not defined
[2022-09-13 17:08:07 +0530] [349890] [INFO] Handling signal: term
[2022-09-13 17:08:07 +0530] [349891] [INFO] Worker exiting (pid: 349891)
[2022-09-13 17:08:07 +0530] [349890] [INFO] Shutting down: Master
[2022-09-13 17:08:08 +0530] [349974] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:08:08 +0530] [349974] [INFO] Listening at: http://0.0.0.0:5080 (349974)
[2022-09-13 17:08:08 +0530] [349974] [INFO] Using worker: sync
[2022-09-13 17:08:08 +0530] [349975] [INFO] Booting worker with pid: 349975
